### ISSUE TITLE
Swim Distance

### ISSUE THREAD

**Issue by bazzadj** [pmprog/pmTriathlon#11]
I have been using the Tri App for open water swimming on the vivoactive.
The map displayed on Garmin Connect is accurate, however the distance is reading 30 to 50% more compared to a 920XT.

**Comment by pmprog** [comment]
People have commented a lot on swim accuracy. Unfortunately, none of this detail is produced by my application - it's provided to my application by Garmin's code. So there's absolutely nothing I can do about this.

Sorry

**Comment by bazzadj** [comment]
Thanks Marq

Unfortunately it's wrong

Any chance of a straight open water swim app?

Barry

**Comment by pmprog** [comment]
I might consider one, but the distance reading will still be inaccurate. I haven't done any development for the Garmin watches for a while, and don't have much time at the minute, so I can't guarentee one, or when it'll be available
