### ISSUE TITLE
Fit file

### ISSUE THREAD

**Issue by ravenfeld** [pmprog/pmTriathlon#12]
Hi, I wanted to know if her create a single file or several did.
It works on fenix 3?
I have not yet fenix 3 but I know that the watch is limited to 3 sports unless I practice so I RAID and X sports.
thank you

**Comment by trijohn** [comment]
I believe it works with any square watch. You will need to test. 

Not sure about how many fit files it creates but does separate disaplines when viewed in Garmin connect.
Please note, there seems to be an issue with the watch app exiting prematurely in the T1 phase. Something I have been looking into and trying to resolve. 

John

**Comment by ravenfeld** [comment]
Thank you
----
Alexis LECANU
06 20 31 01 56

**Comment by pmprog** [comment]
It creates one fit file for each activity, because there was no way to change activity mid-recording.
And yes, it should work with any square watch, though I've only tried it with the Vivoactive
