### ISSUE TITLE
Application restarts watch

### ISSUE THREAD

**Issue by Monolo1** [pmprog/pmTriathlon#8]
Application forces Vivoactive watch to restart when clicking right button at start of discipline.  I have uninstalled and reinstalled the app many times without prevail.

**Comment by pmprog** [comment]
What version of the VA firmware are you running? The reboots are usually because the watch hasn't been updated

**Comment by Monolo1** [comment]
How can I tell?  

Regards,

Martin Wetzler
Martin.wetzler@gmail.com

**Comment by pmprog** [comment]
Go into Settings -> System -> About.
It should give you an ID followed by a version number. Also depending on your version, it should also say "Connect IQ: " and a number, this is the CIQ version

**Comment by Monolo1** [comment]
Version 2.40

How do I upgrade with iPhone 6?

Regards,

Martin Wetzler
Martin.wetzler@gmail.com

**Comment by pmprog** [comment]
I don't know. You might need to plug it into a computer with Garmin Connect Express installed. But your version is more than likely the problem

**Comment by pmprog** [comment]
I assume this worked?

**Comment by Monolo1** [comment]
Thanks yes it did work.

Regards,

Martin Wetzler
Martin.wetzler@gmail.com
